### PR TITLE
Updated all vars in test files to consts and lets.

### PR DESCRIPTION
**Pull request by barrymichaeldoyle**
It's better to define variables as consts and lets over vars.

### CODE REVIEW

**Comment by barrymichaeldoyle** [comment]
Doesn't the babel preset sort that out?

**Comment by ljharb** [comment]
In the test files, i suppose, but none of the production files in this repo get run through babel.

**Comment by barrymichaeldoyle** [comment]
Ah right, didn't realize that. I'll update the PR to only update the tests.

**Comment by barrymichaeldoyle** [comment]
There we go, I reset back to the commits that only affect the test files 👍

**Comment by gaearon** [comment]
Seems fine, thanks. A PR adding a Babel step would also be great!

**Pull request merged**
