### PR TITLE
Update to newest version

### PR DESCRIPTION
**Pull request by MichaelBuessemeyer**
Synched upstream changes from facebook/prop-types to update to latest version commit

### CODE REVIEW

**Comment by MichaelBuessemeyer** [comment]
Sorry my bad, wrong origin

**Comment by ljharb** [comment]
Why is a fork needed? What changes are you trying to add?

**Comment by MichaelBuessemeyer** [comment]
Sorry for this PR. I accidentally opened it to the original repo as Github configures this a default :/ So please ignore this PR.
> What changes are you trying to add?

We modified type-props to include the warnings even in production. Each `process.env.NODE_ENV !== 'production'` is replaced with `true`.

**Comment by ljharb** [comment]
Gotcha. That's something you can do transparently with a bundler without the need to fork, fwiw :-)

**Pull request closed without merging**
