### PR TITLE
Additional ESLint rules & Fix typo in factoryWithTypeCheckers.js

### PR DESCRIPTION
**Pull request by KonstHardy**
I've improved the documentation to fix some minor typos in this PR

Additional ESLint rules:  "no-multi-spaces": ["error"], "key-spacing": ["error"]
"no-multi-spaces" - Disallow multiple spaces;
"key-spacing" - Enforce consistent spacing between keys and values in object literal properties;

### CODE REVIEW

**Comment by ljharb** [comment]
@KonstHardy unfortunately by deleting your fork, this PR is unrecoverable. Please try not to delete forks in the future when there's open PRs for them.

**Comment by KonstHardy** [comment]
@ljharb Sorry that I deleted my fork. 
If my changes to ESLint rules were correct, then I can create a new PR for them

**Comment by ljharb** [comment]
They seem fine, yes

**Comment by KonstHardy** [comment]
Thanks for your reply! I created  a new PR #360

**Pull request closed without merging**
