### PR TITLE
Readme to Function Components

### PR DESCRIPTION
**Pull request by Levin779**
Since its recommend to define components as functions instead of classes this should be updated.

### CODE REVIEW

**Comment by ljharb** [comment]
Where is that unconditionally recommended?

ErrorBoundary components still must be class components, and there's a number of patterns that remain clearer/cleaner as class components than SFCs with hooks.

**Comment by Levin779** [comment]
Its recommended in the official react docs: “We recommend to define components as functions instead of classes.“ 
[https://beta.reactjs.org/reference/react/Component](https://beta.reactjs.org/reference/react/Component)

**Comment by ljharb** [comment]
Once those docs are out of beta, this seems like a reasonable change.

**Comment by wojtekmaj** [comment]
Well, docs are now out of beta. What do we do?

**Pull request closed without merging**
