### PR TITLE
fixed broken proptypes in prod

### LINKED ISSUE #231: Production build each propType is same instance of shim
We use this `propTypes` for custom elements to make runtime parsing based upon prop-types.

Unfortunately in Production the following is true:

```js
import PropTypes from 'prop-types';

PropTypes.string === PropTypes.bool === PropTypes.number === PropTypes.array === PropTypes.object
// -> true
```

Though this should be false.

Currently the `shim` function is static, It would be better to generate it or use a shim factory.
https://github.com/facebook/prop-types/blob/master/factoryWithThrowingShims.js#L15-L59

### PR DESCRIPTION
**Pull request by AndyOGo**
fixes #231

### CODE REVIEW

**Comment by AndyOGo** [comment]
I just signed the CLA 🎉

**Comment by ljharb** [comment]
See #106.

**Comment by LucaMele** [comment]
@ljharb , please reconsider your desicion and instead of a quick check that is similar to the 106 try to find out what we would like to achive here. We wont have performance impact with this and we are consistant between DEV environment and PROD environment.

**Comment by LucaMele** [comment]
is that not a win win?

**Comment by ljharb** [comment]
@LucaMele this isn't my decision; i'm not a collaborator here. React team members were pretty clear about it on #106 tho.

**Comment by LucaMele** [comment]
Hello @ljharb all right sorry :). Well hope that the react team memebers can give it a second chance then. I guess we can call it best practice if code does not change logic between PROD and DEV

**Comment by ljharb** [comment]
Although I'd prefer this type of fix to go in, closing per https://github.com/facebook/prop-types/pull/106#issuecomment-398443259.

**Pull request closed without merging**
